name: Deploy Math with Yanyan

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Build website
        run: mkdocs build --clean

      - name: Upload website
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v4
